/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visualisasi;

/**
 *
 * @author FASIH
 */
import Teori.Teori;
import Home.Home;
import java.awt.Color;
import config.koneksi;
import java.awt.Graphics;
import static java.lang.Math.sin;
import java.util.List;
import java.sql.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;

public class visualisasi extends javax.swing.JFrame {
    private koneksi db = new koneksi();
    int id_pesan = 1;
    int id_biner = 1;

    /**
     * Creates new form visualisasi
     */
    public visualisasi() {
        initComponents();
        jPanel3.setVisible(false);
        jPanel6.setVisible(false);
    }
    
   
   
    public static String convertStringToBinary(String input) {

        StringBuilder result = new StringBuilder();
        char[] chars = input.toCharArray();
        for (char aChar : chars) {
            result.append(
                    String.format("%8s", Integer.toBinaryString(aChar))   // char -> int, auto-cast
                            .replaceAll(" ", "0")                         // zero pads
            );
        }
        return result.toString();

    }

    public static String prettyBinary(String binary, int blockSize, String separator) {

        List<String> result = new ArrayList<>();
        int index = 0;
        while (index < binary.length()) {
            result.add(binary.substring(index, Math.min(index + blockSize, binary.length())));
            index += blockSize;
        }

        return result.stream().collect(Collectors.joining(separator));
    }
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_home = new javax.swing.JPanel();
        txt_home = new javax.swing.JLabel();
        panel_visualisasi = new javax.swing.JPanel();
        txt_visualisasi = new javax.swing.JLabel();
        panel_teori = new javax.swing.JPanel();
        txt_teori = new javax.swing.JLabel();
        jPanel2 = new panelGambar();
        panel_penerima = new javax.swing.JPanel();
        txt_output = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_dac = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_dac = new javax.swing.JTextArea();
        btn_demodulasi = new javax.swing.JButton();
        jPanel6 = new DemodulasiWave();
        jLabel6 = new javax.swing.JLabel();
        btn_output = new javax.swing.JButton();
        panel_pengirim = new javax.swing.JPanel();
        txt_pesan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_adc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_adc = new javax.swing.JTextArea();
        btn_modulasi = new javax.swing.JButton();
        jPanel3 = new ModulasiWave();
        jLabel5 = new javax.swing.JLabel();
        btn_reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Visualisasi");
        setMinimumSize(new java.awt.Dimension(1280, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panel_home.setBackground(new java.awt.Color(255, 255, 255));
        panel_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_homeMouseExited(evt);
            }
        });

        txt_home.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        txt_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_home.setText("Home");

        javax.swing.GroupLayout panel_homeLayout = new javax.swing.GroupLayout(panel_home);
        panel_home.setLayout(panel_homeLayout);
        panel_homeLayout.setHorizontalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_home, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
        );
        panel_homeLayout.setVerticalGroup(
            panel_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_home, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        panel_visualisasi.setBackground(new java.awt.Color(243, 247, 251));
        panel_visualisasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_visualisasiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_visualisasiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_visualisasiMouseExited(evt);
            }
        });

        txt_visualisasi.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        txt_visualisasi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_visualisasi.setText("Visualisasi");

        javax.swing.GroupLayout panel_visualisasiLayout = new javax.swing.GroupLayout(panel_visualisasi);
        panel_visualisasi.setLayout(panel_visualisasiLayout);
        panel_visualisasiLayout.setHorizontalGroup(
            panel_visualisasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_visualisasi, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
        );
        panel_visualisasiLayout.setVerticalGroup(
            panel_visualisasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_visualisasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel_teori.setBackground(new java.awt.Color(255, 255, 255));
        panel_teori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_teoriMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_teoriMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_teoriMouseExited(evt);
            }
        });

        txt_teori.setBackground(new java.awt.Color(255, 255, 255));
        txt_teori.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        txt_teori.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_teori.setText("Teori");

        javax.swing.GroupLayout panel_teoriLayout = new javax.swing.GroupLayout(panel_teori);
        panel_teori.setLayout(panel_teoriLayout);
        panel_teoriLayout.setHorizontalGroup(
            panel_teoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_teori, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        panel_teoriLayout.setVerticalGroup(
            panel_teoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_teori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_visualisasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_teori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 753, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_teori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_visualisasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(243, 247, 251));

        panel_penerima.setBorder(javax.swing.BorderFactory.createTitledBorder("Penerima"));
        panel_penerima.setOpaque(false);

        txt_output.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        txt_output.setBorder(null);
        txt_output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_outputActionPerformed(evt);
            }
        });

        jLabel3.setText("Output PEsan");

        btn_dac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_dac.png"))); // NOI18N
        btn_dac.setBorder(null);
        btn_dac.setBorderPainted(false);
        btn_dac.setContentAreaFilled(false);
        btn_dac.setDefaultCapable(false);
        btn_dac.setFocusPainted(false);
        btn_dac.setFocusable(false);
        btn_dac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dacMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dacMouseExited(evt);
            }
        });
        btn_dac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dacActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel4.setText("=");

        txt_dac.setEditable(false);
        txt_dac.setColumns(20);
        txt_dac.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        txt_dac.setLineWrap(true);
        txt_dac.setRows(5);
        txt_dac.setWrapStyleWord(true);
        txt_dac.setBorder(null);
        txt_dac.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_dac.setFocusable(false);
        txt_dac.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(txt_dac);

        btn_demodulasi.setBackground(new java.awt.Color(243, 247, 251));
        btn_demodulasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_demodulasi.png"))); // NOI18N
        btn_demodulasi.setBorder(null);
        btn_demodulasi.setBorderPainted(false);
        btn_demodulasi.setContentAreaFilled(false);
        btn_demodulasi.setFocusPainted(false);
        btn_demodulasi.setFocusable(false);
        btn_demodulasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_demodulasiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_demodulasiMouseExited(evt);
            }
        });
        btn_demodulasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_demodulasiActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/antena_penerima.png"))); // NOI18N

        btn_output.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_output.png"))); // NOI18N
        btn_output.setBorderPainted(false);
        btn_output.setContentAreaFilled(false);
        btn_output.setFocusPainted(false);
        btn_output.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_outputMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_outputMouseExited(evt);
            }
        });
        btn_output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_outputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_penerimaLayout = new javax.swing.GroupLayout(panel_penerima);
        panel_penerima.setLayout(panel_penerimaLayout);
        panel_penerimaLayout.setHorizontalGroup(
            panel_penerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_penerimaLayout.createSequentialGroup()
                .addGroup(panel_penerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_penerimaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(btn_demodulasi, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(panel_penerimaLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(panel_penerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_penerimaLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panel_penerimaLayout.createSequentialGroup()
                                .addGroup(panel_penerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_output, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addGap(42, 42, 42)
                                .addGroup(panel_penerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_dac, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(btn_output, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(8, 8, 8)))))
                .addContainerGap())
        );
        panel_penerimaLayout.setVerticalGroup(
            panel_penerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_penerimaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addGroup(panel_penerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_output, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_output))
                .addGap(18, 18, 18)
                .addGroup(panel_penerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_penerimaLayout.createSequentialGroup()
                        .addGroup(panel_penerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_penerimaLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_penerimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_demodulasi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(btn_dac))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        panel_pengirim.setBorder(javax.swing.BorderFactory.createTitledBorder("Pengirim"));
        panel_pengirim.setOpaque(false);

        txt_pesan.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        txt_pesan.setBorder(null);
        txt_pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pesanActionPerformed(evt);
            }
        });

        jLabel1.setText("Input Pesan");

        btn_adc.setBackground(new java.awt.Color(243, 247, 251));
        btn_adc.setForeground(new java.awt.Color(243, 247, 251));
        btn_adc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_adc.png"))); // NOI18N
        btn_adc.setBorder(null);
        btn_adc.setBorderPainted(false);
        btn_adc.setContentAreaFilled(false);
        btn_adc.setFocusable(false);
        btn_adc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_adcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_adcMouseExited(evt);
            }
        });
        btn_adc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adcActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel2.setText("=");

        txt_adc.setEditable(false);
        txt_adc.setColumns(20);
        txt_adc.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        txt_adc.setLineWrap(true);
        txt_adc.setRows(5);
        txt_adc.setWrapStyleWord(true);
        txt_adc.setBorder(null);
        txt_adc.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(txt_adc);

        btn_modulasi.setBackground(new java.awt.Color(243, 247, 251));
        btn_modulasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_modulasi.png"))); // NOI18N
        btn_modulasi.setBorder(null);
        btn_modulasi.setBorderPainted(false);
        btn_modulasi.setContentAreaFilled(false);
        btn_modulasi.setFocusable(false);
        btn_modulasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_modulasiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_modulasiMouseExited(evt);
            }
        });
        btn_modulasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modulasiActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setAlignmentX(1.0F);
        jPanel3.setPreferredSize(new java.awt.Dimension(537, 186));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 178, Short.MAX_VALUE)
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/antena_pengirim.png"))); // NOI18N

        javax.swing.GroupLayout panel_pengirimLayout = new javax.swing.GroupLayout(panel_pengirim);
        panel_pengirim.setLayout(panel_pengirimLayout);
        panel_pengirimLayout.setHorizontalGroup(
            panel_pengirimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pengirimLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panel_pengirimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_pesan)
                    .addGroup(panel_pengirimLayout.createSequentialGroup()
                        .addComponent(btn_adc, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                    .addGroup(panel_pengirimLayout.createSequentialGroup()
                        .addGroup(panel_pengirimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(panel_pengirimLayout.createSequentialGroup()
                                .addComponent(btn_modulasi, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        panel_pengirimLayout.setVerticalGroup(
            panel_pengirimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pengirimLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(txt_pesan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_pengirimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_pengirimLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_adc))
                .addGap(18, 18, 18)
                .addGroup(panel_pengirimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_modulasi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn_reset.png"))); // NOI18N
        btn_reset.setBorder(null);
        btn_reset.setBorderPainted(false);
        btn_reset.setContentAreaFilled(false);
        btn_reset.setDefaultCapable(false);
        btn_reset.setFocusPainted(false);
        btn_reset.setFocusable(false);
        btn_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_resetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_resetMouseExited(evt);
            }
        });
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(panel_pengirim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(29, 29, 29)
                        .addComponent(panel_penerima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_pengirim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_penerima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btn_reset)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panel_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_homeMouseEntered
        panel_home.setBackground(Color.decode("#F3F7FB"));
    }//GEN-LAST:event_panel_homeMouseEntered

    private void panel_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_homeMouseExited
        panel_home.setBackground(null);
    }//GEN-LAST:event_panel_homeMouseExited

    private void panel_visualisasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_visualisasiMouseEntered
        panel_visualisasi.setBackground(Color.decode("#F3F7FB"));
    }//GEN-LAST:event_panel_visualisasiMouseEntered

    private void panel_visualisasiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_visualisasiMouseExited
        panel_visualisasi.setBackground(Color.decode("#F3F7FB"));
    }//GEN-LAST:event_panel_visualisasiMouseExited

    private void panel_teoriMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_teoriMouseEntered
        panel_teori.setBackground(Color.decode("#F3F7FB"));
    }//GEN-LAST:event_panel_teoriMouseEntered

    private void panel_teoriMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_teoriMouseExited
        panel_teori.setBackground(null);
    }//GEN-LAST:event_panel_teoriMouseExited

    private void panel_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_homeMouseClicked
        Home hm = new Home();
        hm.setVisible(true);
        hm.pack();
        hm.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_panel_homeMouseClicked

    private void panel_visualisasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_visualisasiMouseClicked
        visualisasi vs = new visualisasi();
        vs.setVisible(true);
        vs.pack();
        vs.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_panel_visualisasiMouseClicked

    private void txt_pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pesanActionPerformed

    private void btn_adcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adcActionPerformed
        String pesan = txt_pesan.getText();
        String result = convertStringToBinary(pesan);
        
        

        
        //insert pesan
        try {
            String query = "insert into pesan (pesan) values ('"+txt_pesan.getText()+"')";
            PreparedStatement ps = db.koneksidb().prepareStatement(query);
            ps.execute();
            
            //set biner
            txt_adc.setText(prettyBinary(result, 8, " "));
            
            //find id
            String query1 = "SELECT max(pesan.id_pesan) as id_pesan FROM pesan";
            PreparedStatement ps1 = db.koneksidb().prepareStatement(query1);
            ResultSet rs1 = ps1.executeQuery();
            rs1.next();           
            id_pesan = rs1.getInt("id_pesan");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "insert pesan gagal"+e);
        }
        //insert detile pesan pengirim
        try {
            String query = "insert into detile_pengirim_pesan (id_pesan,id_pengirim) values ("+(id_pesan)+",1)";
            PreparedStatement ps = db.koneksidb().prepareStatement(query);
            ps.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "insert detile_pesan gagal"+e);
        }
        
        //convert to biner
        try {
            String query = "insert into biner (biner_pesan) values ('"+txt_adc.getText()+"')";
            PreparedStatement ps = db.koneksidb().prepareStatement(query);
            ps.execute();
            
            //id_biner
            String query1 = "SELECT max(biner.id_biner) as id_biner FROM biner";
            PreparedStatement ps1 = db.koneksidb().prepareStatement(query1);
            ResultSet rs1 = ps1.executeQuery();
            rs1.next();
            //find biner id
            id_biner = rs1.getInt("id_biner");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "insert to biner gagal"+e);
        }
        
        
        
        //insert detile biner
         try {
            String query = "insert into detile_biner (id_biner,id_pesan) values ("+id_biner+","+id_pesan+")";
            PreparedStatement ps = db.koneksidb().prepareStatement(query);
            ps.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "insert detile_binaey gagal"+e);
        }
    }//GEN-LAST:event_btn_adcActionPerformed

    private void btn_modulasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modulasiActionPerformed
        jPanel3.setVisible(true);

    }//GEN-LAST:event_btn_modulasiActionPerformed

    private void txt_outputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_outputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_outputActionPerformed

    private void btn_dacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dacActionPerformed

        
         try {
            String sql = "SELECT biner_pesan from biner where id_biner="+id_biner+"";
            PreparedStatement ps = db.koneksidb().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            rs.next();
            txt_dac.setText(rs.getString("biner_pesan"));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "gagal melakukakn demodulasi"+e);
        }
    }//GEN-LAST:event_btn_dacActionPerformed

    private void btn_demodulasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_demodulasiActionPerformed
       jPanel6.setVisible(true);
    }//GEN-LAST:event_btn_demodulasiActionPerformed

    private void btn_adcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adcMouseEntered
        btn_adc.setSize(129,60);
    }//GEN-LAST:event_btn_adcMouseEntered

    private void btn_adcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adcMouseExited
        btn_adc.setSize(129,57);
    }//GEN-LAST:event_btn_adcMouseExited

    private void btn_modulasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modulasiMouseEntered
        btn_modulasi.setSize(235,60);
    }//GEN-LAST:event_btn_modulasiMouseEntered

    private void btn_modulasiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modulasiMouseExited
        btn_modulasi.setSize(235,55);
    }//GEN-LAST:event_btn_modulasiMouseExited

    private void btn_dacMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dacMouseEntered
        btn_dac.setSize(130,60);
    }//GEN-LAST:event_btn_dacMouseEntered

    private void btn_dacMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dacMouseExited
        btn_dac.setSize(130,55);
    }//GEN-LAST:event_btn_dacMouseExited

    private void btn_demodulasiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_demodulasiMouseEntered
        btn_demodulasi.setSize(286,60);
    }//GEN-LAST:event_btn_demodulasiMouseEntered

    private void btn_demodulasiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_demodulasiMouseExited
        btn_demodulasi.setSize(286,55);
    }//GEN-LAST:event_btn_demodulasiMouseExited

    private void btn_resetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMouseEntered
        btn_reset.setSize(130, 60);
    }//GEN-LAST:event_btn_resetMouseEntered

    private void btn_resetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMouseExited
        btn_reset.setSize(130, 56);
    }//GEN-LAST:event_btn_resetMouseExited

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        txt_pesan.setText("");
        txt_adc.setText("");
        jPanel3.setVisible(false);
        jPanel6.setVisible(false);
        txt_dac.setText("");
        txt_output.setText("");
    }//GEN-LAST:event_btn_resetActionPerformed

    private void panel_teoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_teoriMouseClicked
        Teori ab = new Teori();
        ab.setVisible(true);
        ab.pack();
        ab.setLocationRelativeTo(null);
        dispose();  
    }//GEN-LAST:event_panel_teoriMouseClicked

    private void btn_outputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_outputActionPerformed
        String biner = txt_dac.getText();
        String[] parts = biner.split(" ");
        StringBuilder sb = new StringBuilder();

        for (String part : parts) {
            int val = Integer.parseInt(part, 2);
            String c = Character.toString((char)val);
            sb.append(c);
        }
        txt_output.setText(sb.toString());
    }//GEN-LAST:event_btn_outputActionPerformed

    private void btn_outputMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_outputMouseEntered
        btn_output.setSize(130,60);
    }//GEN-LAST:event_btn_outputMouseEntered

    private void btn_outputMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_outputMouseExited
        btn_output.setSize(130,55);
    }//GEN-LAST:event_btn_outputMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(visualisasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(visualisasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(visualisasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(visualisasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new visualisasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adc;
    private javax.swing.JButton btn_dac;
    private javax.swing.JButton btn_demodulasi;
    private javax.swing.JButton btn_modulasi;
    private javax.swing.JButton btn_output;
    private javax.swing.JButton btn_reset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panel_home;
    private javax.swing.JPanel panel_penerima;
    private javax.swing.JPanel panel_pengirim;
    private javax.swing.JPanel panel_teori;
    private javax.swing.JPanel panel_visualisasi;
    private javax.swing.JTextArea txt_adc;
    private javax.swing.JTextArea txt_dac;
    private javax.swing.JLabel txt_home;
    private javax.swing.JTextField txt_output;
    private javax.swing.JTextField txt_pesan;
    private javax.swing.JLabel txt_teori;
    private javax.swing.JLabel txt_visualisasi;
    // End of variables declaration//GEN-END:variables
}
