/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Backup;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;

/**
 *
 * @author riza5
 */
public class About_plan extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    public About_plan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        LOGO = new javax.swing.JLabel();
        btn_home = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        btn_vis = new javax.swing.JPanel();
        vis = new javax.swing.JLabel();
        btn_tentang = new javax.swing.JPanel();
        ten = new javax.swing.JLabel();
        garis = new javax.swing.JPanel();
        jPANEL2 = new komponen.JPANEL();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Menu.setBackground(new java.awt.Color(41, 41, 41));
        Menu.setPreferredSize(new java.awt.Dimension(150, 0));

        LOGO.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        LOGO.setForeground(new java.awt.Color(255, 102, 51));
        LOGO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGO.setText("APPEKS");

        btn_home.setBackground(new java.awt.Color(51, 51, 51));
        btn_home.setMinimumSize(new java.awt.Dimension(160, 100));
        btn_home.setPreferredSize(new java.awt.Dimension(150, 50));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
        });

        home.setBackground(new java.awt.Color(0, 0, 0));
        home.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setText("HOME");
        home.setMaximumSize(new java.awt.Dimension(1000, 1000));
        home.setMinimumSize(new java.awt.Dimension(100, 50));
        home.setPreferredSize(new java.awt.Dimension(100, 50));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_homeLayout = new javax.swing.GroupLayout(btn_home);
        btn_home.setLayout(btn_homeLayout);
        btn_homeLayout.setHorizontalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btn_homeLayout.setVerticalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_vis.setBackground(new java.awt.Color(51, 51, 51));
        btn_vis.setPreferredSize(new java.awt.Dimension(150, 50));
        btn_vis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_visMouseEntered(evt);
            }
        });

        vis.setBackground(new java.awt.Color(0, 0, 0));
        vis.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        vis.setForeground(new java.awt.Color(255, 255, 255));
        vis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vis.setText("VISUALISASI");
        vis.setMaximumSize(new java.awt.Dimension(1000, 1000));
        vis.setMinimumSize(new java.awt.Dimension(100, 50));
        vis.setPreferredSize(new java.awt.Dimension(100, 50));
        vis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                visMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                visMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_visLayout = new javax.swing.GroupLayout(btn_vis);
        btn_vis.setLayout(btn_visLayout);
        btn_visLayout.setHorizontalGroup(
            btn_visLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_visLayout.createSequentialGroup()
                .addComponent(vis, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        btn_visLayout.setVerticalGroup(
            btn_visLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_tentang.setBackground(new java.awt.Color(51, 51, 51));
        btn_tentang.setPreferredSize(new java.awt.Dimension(150, 50));
        btn_tentang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_tentangMouseEntered(evt);
            }
        });

        ten.setBackground(new java.awt.Color(0, 0, 0));
        ten.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ten.setForeground(new java.awt.Color(255, 255, 255));
        ten.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ten.setText("TENTANG");
        ten.setMaximumSize(new java.awt.Dimension(1000, 1000));
        ten.setMinimumSize(new java.awt.Dimension(100, 50));
        ten.setPreferredSize(new java.awt.Dimension(100, 50));
        ten.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tenMouseExited(evt);
            }
        });

        garis.setBackground(new java.awt.Color(255, 102, 51));
        garis.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout garisLayout = new javax.swing.GroupLayout(garis);
        garis.setLayout(garisLayout);
        garisLayout.setHorizontalGroup(
            garisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        garisLayout.setVerticalGroup(
            garisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btn_tentangLayout = new javax.swing.GroupLayout(btn_tentang);
        btn_tentang.setLayout(btn_tentangLayout);
        btn_tentangLayout.setHorizontalGroup(
            btn_tentangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_tentangLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(garis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ten, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
        );
        btn_tentangLayout.setVerticalGroup(
            btn_tentangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_tentangLayout.createSequentialGroup()
                .addComponent(garis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPANEL2.setForeground(new java.awt.Color(255, 255, 255));
        jPANEL2.setRoundTopLeft(50);
        jPANEL2.setRoundqBottomLeft(50);

        jScrollPane1.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("Proses dalam sistem komunikasi wireless :\n1. Pengirim memasukan pesan teks dan mengirimkan pesan tersebut.\n2. Pesan tersebut akan dikonversi menjadi bentuk binary menggunakan ADC\n3. Data binary akan dimodulasikan melalui antena\n4. Sinyal yang keluar akan dibawa oleh carier untuk dikirim ke penerima dan berbentuk sinyal informasi.\n5. Saat sinyal mencapai ke penerima, sinyal informasi akan di demodulasi menjadi binary menggunakan DAC\n6. Pesan yang diterima akan sesuai dengan pesan saat dikirim");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPANEL2Layout = new javax.swing.GroupLayout(jPANEL2);
        jPANEL2.setLayout(jPANEL2Layout);
        jPANEL2Layout.setHorizontalGroup(
            jPANEL2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPANEL2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1075, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        jPANEL2Layout.setVerticalGroup(
            jPANEL2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPANEL2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_vis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tentang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LOGO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPANEL2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPANEL2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_vis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_tentang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(476, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        Home_plan hm = new Home_plan();
        hm.setVisible(true);
        hm.pack();
        hm.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        btn_home.setBackground(new Color(224, 106, 2));
        
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        btn_home.setBackground(new Color(51,51,51));
        
    }//GEN-LAST:event_homeMouseExited

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered

    }//GEN-LAST:event_btn_homeMouseEntered

    private void visMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visMouseEntered
        btn_vis.setBackground(new Color(224, 106, 2));
       
    }//GEN-LAST:event_visMouseEntered

    private void visMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visMouseExited
        btn_vis.setBackground(new Color(51,51,51));
       
    }//GEN-LAST:event_visMouseExited

    private void btn_visMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_visMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_visMouseEntered

    private void tenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tenMouseEntered
        btn_tentang.setBackground(new Color(224, 106, 2));
         garis.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_tenMouseEntered

    private void tenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tenMouseExited
        btn_tentang.setBackground(new Color(51,51,51));
         garis.setBackground(new Color(255,102,51));
    }//GEN-LAST:event_tenMouseExited

    private void btn_tentangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tentangMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tentangMouseEntered

    private void visMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visMouseClicked
       Visualisasi_plan vs = new Visualisasi_plan();
        vs.setVisible(true);
        vs.pack();
        vs.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_visMouseClicked

    private void tenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tenMouseClicked
        About_plan ab = new About_plan();
        ab.setVisible(true);
        ab.pack();
        ab.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_tenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About_plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About_plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About_plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About_plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        FlatDarkLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About_plan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGO;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel btn_home;
    private javax.swing.JPanel btn_tentang;
    private javax.swing.JPanel btn_vis;
    private javax.swing.JPanel garis;
    private javax.swing.JLabel home;
    private komponen.JPANEL jPANEL2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel ten;
    private javax.swing.JLabel vis;
    // End of variables declaration//GEN-END:variables
}
