/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Backup;

import Backup.*;
import Main.*;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;

/**
 *
 * @author riza5
 */
public class Visualisasi_plan extends javax.swing.JFrame {

    /**
     * Creates new form Visualisasi
     */
    public Visualisasi_plan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        LOGO = new javax.swing.JLabel();
        btn_home = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        btn_vis = new javax.swing.JPanel();
        vis = new javax.swing.JLabel();
        garis = new javax.swing.JPanel();
        btn_tentang = new javax.swing.JPanel();
        ten = new javax.swing.JLabel();
        jPANEL2 = new komponen.JPANEL();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        Pengirim = new javax.swing.JLabel();
        Pesan = new javax.swing.JLabel();
        ScrollPesan = new javax.swing.JScrollPane();
        pesanArea = new javax.swing.JTextArea();
        PanahKanan = new javax.swing.JLabel();
        ADC_btn = new komponen.JPANEL();
        jLabel3 = new javax.swing.JLabel();
        BinaryPesan = new javax.swing.JLabel();
        ScrollBinary = new javax.swing.JScrollPane();
        BinaryKirim = new javax.swing.JTextArea();
        Modulasi = new javax.swing.JLabel();
        ModulasiSignal = new javax.swing.JPanel();
        Demodulasi = new javax.swing.JLabel();
        DemodulasiSignal = new javax.swing.JPanel();
        Pengirim1 = new javax.swing.JLabel();
        Pesan1 = new javax.swing.JLabel();
        ScrollPesan1 = new javax.swing.JScrollPane();
        pesanArea1 = new javax.swing.JTextArea();
        PanahKanan1 = new javax.swing.JLabel();
        ADC_btn1 = new komponen.JPANEL();
        jLabel4 = new javax.swing.JLabel();
        BinaryPesan1 = new javax.swing.JLabel();
        ScrollBinary1 = new javax.swing.JScrollPane();
        BinaryKirim1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Menu.setBackground(new java.awt.Color(41, 41, 41));
        Menu.setPreferredSize(new java.awt.Dimension(150, 0));

        LOGO.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        LOGO.setForeground(new java.awt.Color(255, 102, 51));
        LOGO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGO.setText("APPEKS");

        btn_home.setBackground(new java.awt.Color(51, 51, 51));
        btn_home.setMinimumSize(new java.awt.Dimension(160, 100));
        btn_home.setPreferredSize(new java.awt.Dimension(150, 50));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
        });

        home.setBackground(new java.awt.Color(0, 0, 0));
        home.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setText("HOME");
        home.setMaximumSize(new java.awt.Dimension(1000, 1000));
        home.setMinimumSize(new java.awt.Dimension(100, 50));
        home.setPreferredSize(new java.awt.Dimension(100, 50));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_homeLayout = new javax.swing.GroupLayout(btn_home);
        btn_home.setLayout(btn_homeLayout);
        btn_homeLayout.setHorizontalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btn_homeLayout.setVerticalGroup(
            btn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_vis.setBackground(new java.awt.Color(51, 51, 51));
        btn_vis.setPreferredSize(new java.awt.Dimension(150, 50));
        btn_vis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_visMouseEntered(evt);
            }
        });

        vis.setBackground(new java.awt.Color(0, 0, 0));
        vis.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        vis.setForeground(new java.awt.Color(255, 255, 255));
        vis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vis.setText("VISUALISASI");
        vis.setMaximumSize(new java.awt.Dimension(1000, 1000));
        vis.setMinimumSize(new java.awt.Dimension(100, 50));
        vis.setPreferredSize(new java.awt.Dimension(100, 50));
        vis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                visMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                visMouseExited(evt);
            }
        });

        garis.setBackground(new java.awt.Color(255, 102, 51));
        garis.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout garisLayout = new javax.swing.GroupLayout(garis);
        garis.setLayout(garisLayout);
        garisLayout.setHorizontalGroup(
            garisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        garisLayout.setVerticalGroup(
            garisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btn_visLayout = new javax.swing.GroupLayout(btn_vis);
        btn_vis.setLayout(btn_visLayout);
        btn_visLayout.setHorizontalGroup(
            btn_visLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_visLayout.createSequentialGroup()
                .addComponent(garis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(vis, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        btn_visLayout.setVerticalGroup(
            btn_visLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_visLayout.createSequentialGroup()
                .addComponent(garis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btn_tentang.setBackground(new java.awt.Color(51, 51, 51));
        btn_tentang.setPreferredSize(new java.awt.Dimension(150, 50));
        btn_tentang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_tentangMouseEntered(evt);
            }
        });

        ten.setBackground(new java.awt.Color(0, 0, 0));
        ten.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ten.setForeground(new java.awt.Color(255, 255, 255));
        ten.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ten.setText("TENTANG");
        ten.setMaximumSize(new java.awt.Dimension(1000, 1000));
        ten.setMinimumSize(new java.awt.Dimension(100, 50));
        ten.setPreferredSize(new java.awt.Dimension(100, 50));
        ten.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tenMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btn_tentangLayout = new javax.swing.GroupLayout(btn_tentang);
        btn_tentang.setLayout(btn_tentangLayout);
        btn_tentangLayout.setHorizontalGroup(
            btn_tentangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_tentangLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(ten, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
        );
        btn_tentangLayout.setVerticalGroup(
            btn_tentangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPANEL2.setForeground(new java.awt.Color(255, 255, 255));
        jPANEL2.setRoundTopLeft(50);
        jPANEL2.setRoundqBottomLeft(50);

        jPanel3.setPreferredSize(new java.awt.Dimension(1280, 3000));

        Pengirim.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Pengirim.setForeground(new java.awt.Color(255, 255, 255));
        Pengirim.setText("Pengirim");

        Pesan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Pesan.setForeground(new java.awt.Color(255, 255, 255));
        Pesan.setText("Pesan: ");

        pesanArea.setColumns(20);
        pesanArea.setForeground(new java.awt.Color(255, 255, 255));
        pesanArea.setLineWrap(true);
        pesanArea.setRows(5);
        pesanArea.setMinimumSize(new java.awt.Dimension(400, 200));
        pesanArea.setPreferredSize(new java.awt.Dimension(400, 200));
        ScrollPesan.setViewportView(pesanArea);

        PanahKanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Arrow_Left_LG.png"))); // NOI18N

        ADC_btn.setForeground(new java.awt.Color(255, 255, 255));
        ADC_btn.setRoundTopLeft(15);
        ADC_btn.setRoundqBottomLeft(15);
        ADC_btn.setRoundqBottomRight(15);
        ADC_btn.setRoundqTopRight(15);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ADC");

        javax.swing.GroupLayout ADC_btnLayout = new javax.swing.GroupLayout(ADC_btn);
        ADC_btn.setLayout(ADC_btnLayout);
        ADC_btnLayout.setHorizontalGroup(
            ADC_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
        );
        ADC_btnLayout.setVerticalGroup(
            ADC_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        BinaryPesan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BinaryPesan.setForeground(new java.awt.Color(255, 255, 255));
        BinaryPesan.setText("Binary Pesan:");

        BinaryKirim.setEditable(false);
        BinaryKirim.setColumns(20);
        BinaryKirim.setForeground(new java.awt.Color(255, 255, 255));
        BinaryKirim.setLineWrap(true);
        BinaryKirim.setRows(5);
        BinaryKirim.setMinimumSize(new java.awt.Dimension(400, 200));
        BinaryKirim.setPreferredSize(new java.awt.Dimension(400, 200));
        ScrollBinary.setViewportView(BinaryKirim);

        Modulasi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Modulasi.setForeground(new java.awt.Color(255, 255, 255));
        Modulasi.setText("Modulasi : ");

        ModulasiSignal.setBackground(new java.awt.Color(255, 255, 255));
        ModulasiSignal.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ModulasiSignalLayout = new javax.swing.GroupLayout(ModulasiSignal);
        ModulasiSignal.setLayout(ModulasiSignalLayout);
        ModulasiSignalLayout.setHorizontalGroup(
            ModulasiSignalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ModulasiSignalLayout.setVerticalGroup(
            ModulasiSignalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        Demodulasi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Demodulasi.setForeground(new java.awt.Color(255, 255, 255));
        Demodulasi.setText("Demodulasi : ");

        DemodulasiSignal.setBackground(new java.awt.Color(255, 255, 255));
        DemodulasiSignal.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout DemodulasiSignalLayout = new javax.swing.GroupLayout(DemodulasiSignal);
        DemodulasiSignal.setLayout(DemodulasiSignalLayout);
        DemodulasiSignalLayout.setHorizontalGroup(
            DemodulasiSignalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DemodulasiSignalLayout.setVerticalGroup(
            DemodulasiSignalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        Pengirim1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Pengirim1.setForeground(new java.awt.Color(255, 255, 255));
        Pengirim1.setText("Penerima");

        Pesan1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Pesan1.setForeground(new java.awt.Color(255, 255, 255));
        Pesan1.setText("Pesan: ");

        pesanArea1.setColumns(20);
        pesanArea1.setForeground(new java.awt.Color(255, 255, 255));
        pesanArea1.setLineWrap(true);
        pesanArea1.setRows(5);
        pesanArea1.setMinimumSize(new java.awt.Dimension(400, 200));
        pesanArea1.setPreferredSize(new java.awt.Dimension(400, 200));
        ScrollPesan1.setViewportView(pesanArea1);

        PanahKanan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Arrow_Left_LG.png"))); // NOI18N

        ADC_btn1.setForeground(new java.awt.Color(255, 255, 255));
        ADC_btn1.setRoundTopLeft(15);
        ADC_btn1.setRoundqBottomLeft(15);
        ADC_btn1.setRoundqBottomRight(15);
        ADC_btn1.setRoundqTopRight(15);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DAC");

        javax.swing.GroupLayout ADC_btn1Layout = new javax.swing.GroupLayout(ADC_btn1);
        ADC_btn1.setLayout(ADC_btn1Layout);
        ADC_btn1Layout.setHorizontalGroup(
            ADC_btn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
        );
        ADC_btn1Layout.setVerticalGroup(
            ADC_btn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        BinaryPesan1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BinaryPesan1.setForeground(new java.awt.Color(255, 255, 255));
        BinaryPesan1.setText("Binary Pesan:");

        BinaryKirim1.setEditable(false);
        BinaryKirim1.setColumns(20);
        BinaryKirim1.setForeground(new java.awt.Color(255, 255, 255));
        BinaryKirim1.setLineWrap(true);
        BinaryKirim1.setRows(5);
        BinaryKirim1.setMinimumSize(new java.awt.Dimension(400, 200));
        BinaryKirim1.setPreferredSize(new java.awt.Dimension(400, 200));
        ScrollBinary1.setViewportView(BinaryKirim1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DemodulasiSignal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModulasiSignal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pesan)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(ScrollPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ADC_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(PanahKanan)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BinaryPesan)
                            .addComponent(ScrollBinary)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Demodulasi)
                            .addComponent(Pengirim1)
                            .addComponent(Pesan1)
                            .addComponent(Pengirim)
                            .addComponent(Modulasi)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(ScrollPesan1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(ADC_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(PanahKanan1)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(BinaryPesan1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ScrollBinary1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))))
                .addGap(306, 306, 306))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(Pengirim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(BinaryPesan)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ScrollBinary))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                .addComponent(PanahKanan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(ADC_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Pesan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ScrollPesan)))
                .addGap(18, 18, 18)
                .addComponent(Modulasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModulasiSignal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Demodulasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DemodulasiSignal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Pengirim1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(BinaryPesan1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ScrollBinary1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(PanahKanan1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(ADC_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Pesan1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ScrollPesan1)))
                .addGap(1747, 1747, 1747))
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout jPANEL2Layout = new javax.swing.GroupLayout(jPANEL2);
        jPANEL2.setLayout(jPANEL2Layout);
        jPANEL2Layout.setHorizontalGroup(
            jPANEL2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPANEL2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1089, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPANEL2Layout.setVerticalGroup(
            jPANEL2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPANEL2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_vis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tentang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LOGO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPANEL2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPANEL2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_vis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_tentang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1272, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 1524, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        Home_plan hm = new Home_plan();
        hm.setVisible(true);
        hm.pack();
        hm.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        btn_home.setBackground(new Color(224, 106, 2));

    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        btn_home.setBackground(new Color(51,51,51));

    }//GEN-LAST:event_homeMouseExited

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered

    }//GEN-LAST:event_btn_homeMouseEntered

    private void visMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visMouseEntered
        btn_vis.setBackground(new Color(224, 106, 2));
        garis.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_visMouseEntered

    private void visMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visMouseExited
        btn_vis.setBackground(new Color(51,51,51));
        garis.setBackground(new Color(255,102,51));

    }//GEN-LAST:event_visMouseExited

    private void btn_visMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_visMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_visMouseEntered

    private void tenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tenMouseEntered
        btn_tentang.setBackground(new Color(224, 106, 2));
        
    }//GEN-LAST:event_tenMouseEntered

    private void tenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tenMouseExited
        btn_tentang.setBackground(new Color(51,51,51));
        
    }//GEN-LAST:event_tenMouseExited

    private void btn_tentangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tentangMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tentangMouseEntered

    private void visMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visMouseClicked
        Visualisasi_plan vs = new Visualisasi_plan();
        vs.setVisible(true);
        vs.pack();
        vs.setLocationRelativeTo(null);
        dispose();
        
    }//GEN-LAST:event_visMouseClicked

    private void tenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tenMouseClicked
        About_plan ab = new About_plan();
        ab.setVisible(true);
        ab.pack();
        ab.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_tenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visualisasi_plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visualisasi_plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visualisasi_plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visualisasi_plan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        FlatDarkLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visualisasi_plan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private komponen.JPANEL ADC_btn;
    private komponen.JPANEL ADC_btn1;
    private javax.swing.JTextArea BinaryKirim;
    private javax.swing.JTextArea BinaryKirim1;
    private javax.swing.JLabel BinaryPesan;
    private javax.swing.JLabel BinaryPesan1;
    private javax.swing.JLabel Demodulasi;
    private javax.swing.JPanel DemodulasiSignal;
    private javax.swing.JLabel LOGO;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel Modulasi;
    private javax.swing.JPanel ModulasiSignal;
    private javax.swing.JLabel PanahKanan;
    private javax.swing.JLabel PanahKanan1;
    private javax.swing.JLabel Pengirim;
    private javax.swing.JLabel Pengirim1;
    private javax.swing.JLabel Pesan;
    private javax.swing.JLabel Pesan1;
    private javax.swing.JScrollPane ScrollBinary;
    private javax.swing.JScrollPane ScrollBinary1;
    private javax.swing.JScrollPane ScrollPesan;
    private javax.swing.JScrollPane ScrollPesan1;
    private javax.swing.JPanel btn_home;
    private javax.swing.JPanel btn_tentang;
    private javax.swing.JPanel btn_vis;
    private javax.swing.JPanel garis;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private komponen.JPANEL jPANEL2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea pesanArea;
    private javax.swing.JTextArea pesanArea1;
    private javax.swing.JLabel ten;
    private javax.swing.JLabel vis;
    // End of variables declaration//GEN-END:variables
}
