/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HOME;

import TEORI.Teori;
import VISUALISASI.Visualisasi;
import java.awt.Color;

/**
 *
 * @author riza5
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MENU = new komponen.JPANEL();
        DASHBOARD = new komponen.JPANEL();
        dsb_label = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        VISUALISASI = new komponen.JPANEL();
        vs_label = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TENTANG = new komponen.JPANEL();
        tr_label = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LOGO = new javax.swing.JLabel();
        logo = new komponen.JPANEL();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JLabel();
        LABEL = new javax.swing.JLabel();
        BODY = new komponen.JPANEL();
        LOGO1 = new javax.swing.JLabel();
        LOGO3 = new javax.swing.JLabel();
        btn_mv = new komponen.JPANEL();
        mv = new javax.swing.JLabel();
        pt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(16, 21, 51));

        MENU.setForeground(new java.awt.Color(47, 53, 103));
        MENU.setPreferredSize(new java.awt.Dimension(331, 690));
        MENU.setRoundTopLeft(30);
        MENU.setRoundqBottomLeft(30);
        MENU.setRoundqBottomRight(30);
        MENU.setRoundqTopRight(30);

        DASHBOARD.setForeground(new java.awt.Color(255, 255, 255));
        DASHBOARD.setPreferredSize(new java.awt.Dimension(278, 59));
        DASHBOARD.setRoundTopLeft(15);
        DASHBOARD.setRoundqBottomLeft(15);
        DASHBOARD.setRoundqBottomRight(15);
        DASHBOARD.setRoundqTopRight(15);
        DASHBOARD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DASHBOARDMouseClicked(evt);
            }
        });

        dsb_label.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        dsb_label.setForeground(new java.awt.Color(47, 53, 103));
        dsb_label.setText("Home");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/komponen/Home_icon.png"))); // NOI18N

        javax.swing.GroupLayout DASHBOARDLayout = new javax.swing.GroupLayout(DASHBOARD);
        DASHBOARD.setLayout(DASHBOARDLayout);
        DASHBOARDLayout.setHorizontalGroup(
            DASHBOARDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DASHBOARDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dsb_label, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
        );
        DASHBOARDLayout.setVerticalGroup(
            DASHBOARDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DASHBOARDLayout.createSequentialGroup()
                .addComponent(dsb_label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(DASHBOARDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        VISUALISASI.setBackground(new java.awt.Color(47, 53, 103));
        VISUALISASI.setForeground(new java.awt.Color(47, 53, 103));
        VISUALISASI.setPreferredSize(new java.awt.Dimension(278, 59));
        VISUALISASI.setRoundTopLeft(15);
        VISUALISASI.setRoundqBottomLeft(15);
        VISUALISASI.setRoundqBottomRight(15);
        VISUALISASI.setRoundqTopRight(15);
        VISUALISASI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VISUALISASIMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VISUALISASIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VISUALISASIMouseExited(evt);
            }
        });

        vs_label.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        vs_label.setForeground(new java.awt.Color(255, 255, 255));
        vs_label.setText("Visualisasi");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/komponen/Message_icon.png"))); // NOI18N

        javax.swing.GroupLayout VISUALISASILayout = new javax.swing.GroupLayout(VISUALISASI);
        VISUALISASI.setLayout(VISUALISASILayout);
        VISUALISASILayout.setHorizontalGroup(
            VISUALISASILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VISUALISASILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vs_label, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        VISUALISASILayout.setVerticalGroup(
            VISUALISASILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vs_label, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
            .addGroup(VISUALISASILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TENTANG.setBackground(new java.awt.Color(47, 53, 103));
        TENTANG.setForeground(new java.awt.Color(47, 53, 103));
        TENTANG.setRoundTopLeft(15);
        TENTANG.setRoundqBottomLeft(15);
        TENTANG.setRoundqBottomRight(15);
        TENTANG.setRoundqTopRight(15);
        TENTANG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TENTANGMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TENTANGMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TENTANGMouseExited(evt);
            }
        });

        tr_label.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        tr_label.setForeground(new java.awt.Color(255, 255, 255));
        tr_label.setText("Teori");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/komponen/Activity_1.png"))); // NOI18N

        javax.swing.GroupLayout TENTANGLayout = new javax.swing.GroupLayout(TENTANG);
        TENTANG.setLayout(TENTANGLayout);
        TENTANGLayout.setHorizontalGroup(
            TENTANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TENTANGLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tr_label, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TENTANGLayout.setVerticalGroup(
            TENTANGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tr_label, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TENTANGLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        LOGO.setBackground(new java.awt.Color(255, 255, 255));
        LOGO.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LOGO.setForeground(new java.awt.Color(255, 81, 81));
        LOGO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGO.setText("APPEKS");

        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setPreferredSize(new java.awt.Dimension(70, 70));
        logo.setRoundTopLeft(100);
        logo.setRoundqBottomLeft(100);
        logo.setRoundqBottomRight(100);
        logo.setRoundqTopRight(100);
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/komponen/side_bar_logo.png"))); // NOI18N

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("<html>Apliksi Pembelajaran Proses Sistem Komunikasi Wireless</html>");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/komponen/logout_icon.png"))); // NOI18N

        btn_logout.setFont(new java.awt.Font("Poppins Medium", 0, 16)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 81, 81));
        btn_logout.setText("Close App");
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MENULayout = new javax.swing.GroupLayout(MENU);
        MENU.setLayout(MENULayout);
        MENULayout.setHorizontalGroup(
            MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MENULayout.createSequentialGroup()
                .addGroup(MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MENULayout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DASHBOARD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(MENULayout.createSequentialGroup()
                                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LOGO)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(MENULayout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addGroup(MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(VISUALISASI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TENTANG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(MENULayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_logout)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        MENULayout.setVerticalGroup(
            MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MENULayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MENULayout.createSequentialGroup()
                        .addComponent(LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(DASHBOARD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(VISUALISASI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TENTANG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MENULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );

        LABEL.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        LABEL.setForeground(new java.awt.Color(255, 255, 255));
        LABEL.setText("Home");

        BODY.setForeground(new java.awt.Color(47, 53, 103));
        BODY.setRoundTopLeft(30);
        BODY.setRoundqBottomLeft(30);
        BODY.setRoundqBottomRight(30);
        BODY.setRoundqTopRight(30);

        LOGO1.setFont(new java.awt.Font("Poppins Medium", 1, 32)); // NOI18N
        LOGO1.setForeground(new java.awt.Color(255, 255, 255));
        LOGO1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGO1.setText("APPEKS");

        LOGO3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LOGO3.setForeground(new java.awt.Color(255, 255, 255));
        LOGO3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btn_mv.setForeground(new java.awt.Color(255, 255, 255));
        btn_mv.setRoundTopLeft(15);
        btn_mv.setRoundqBottomLeft(15);
        btn_mv.setRoundqBottomRight(15);
        btn_mv.setRoundqTopRight(15);
        btn_mv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mvMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_mvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_mvMouseExited(evt);
            }
        });

        mv.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        mv.setForeground(new java.awt.Color(16, 21, 51));
        mv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mv.setText("Mulai Visualisasi");

        javax.swing.GroupLayout btn_mvLayout = new javax.swing.GroupLayout(btn_mv);
        btn_mv.setLayout(btn_mvLayout);
        btn_mvLayout.setHorizontalGroup(
            btn_mvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mv, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btn_mvLayout.setVerticalGroup(
            btn_mvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mv, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pt.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        pt.setForeground(new java.awt.Color(255, 255, 255));
        pt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pt.setText("Pelajari Teori");
        pt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ptMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ptMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poppins Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<html>APPEKS atau aplikasi pemebelajaran proses kominukasi sistem adalah aplikasi yang digunakan untuk menunjang pembelajaran khususnya sistem komunikasi, aplikasi ini terdapat teori tentang komunikasi sistem dan terdapat visulisasi proses komunikasi mulai dari informasi pengirim, adc, modulasi, demodulasi, dac hingga penerima.</html>");

        javax.swing.GroupLayout BODYLayout = new javax.swing.GroupLayout(BODY);
        BODY.setLayout(BODYLayout);
        BODYLayout.setHorizontalGroup(
            BODYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BODYLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(BODYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LOGO3, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BODYLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(BODYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LOGO1)
                            .addGroup(BODYLayout.createSequentialGroup()
                                .addComponent(btn_mv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pt))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1057, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        BODYLayout.setVerticalGroup(
            BODYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BODYLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(LOGO1)
                .addGroup(BODYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BODYLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(LOGO3))
                    .addGroup(BODYLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BODYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html>WIRELESS COMMUNICATION</html>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(MENU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(BODY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addComponent(BODY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(MENU, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VISUALISASIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VISUALISASIMouseEntered
        DASHBOARD.setForeground(new Color(47, 53, 103));

        dsb_label.setForeground(new Color(255,255,255));
        
        VISUALISASI.setForeground(new Color(255,255,255));

        vs_label.setForeground(new Color(47, 53, 103));
    }//GEN-LAST:event_VISUALISASIMouseEntered

    private void VISUALISASIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VISUALISASIMouseExited
        DASHBOARD.setForeground(new Color(255,255,255)); 

        dsb_label.setForeground(new Color(47, 53, 103));
        
        VISUALISASI.setForeground(new Color(47, 53, 103));

        vs_label.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_VISUALISASIMouseExited

    private void TENTANGMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TENTANGMouseEntered
        DASHBOARD.setForeground(new Color(47, 53, 103));

        dsb_label.setForeground(new Color(255,255,255));
        
        TENTANG.setForeground(new Color(255,255,255));

        tr_label.setForeground(new Color(47, 53, 103));
    }//GEN-LAST:event_TENTANGMouseEntered

    private void TENTANGMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TENTANGMouseExited
       DASHBOARD.setForeground(new Color(255,255,255)); 

        dsb_label.setForeground(new Color(47, 53, 103));
        
        TENTANG.setForeground(new Color(47, 53, 103));

        tr_label.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_TENTANGMouseExited

    private void VISUALISASIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VISUALISASIMouseClicked
        Visualisasi vs = new Visualisasi();
        vs.setVisible(true);
        vs.pack();
        vs.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_VISUALISASIMouseClicked

    private void DASHBOARDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DASHBOARDMouseClicked
        Home hm = new Home();
        hm.setVisible(true);
        hm.pack();
        hm.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_DASHBOARDMouseClicked

    private void TENTANGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TENTANGMouseClicked
       Teori tt = new Teori();
        tt.setVisible(true);
        tt.pack();
        tt.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_TENTANGMouseClicked

    private void btn_mvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mvMouseClicked
       Visualisasi vs = new Visualisasi();
        vs.setVisible(true);
        vs.pack();
        vs.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_btn_mvMouseClicked

    private void btn_mvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mvMouseEntered
        btn_mv.setForeground(new Color(0xFF5151));
        mv.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btn_mvMouseEntered

    private void btn_mvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mvMouseExited
        btn_mv.setForeground(new Color(255,255,255));
        mv.setForeground(new Color(16,21,51));
    }//GEN-LAST:event_btn_mvMouseExited

    private void ptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptMouseClicked
        Teori tt = new Teori();
        tt.setVisible(true);
        tt.pack();
        tt.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_ptMouseClicked

    private void ptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptMouseEntered
        pt.setForeground(new Color(0xFF5151));
    }//GEN-LAST:event_ptMouseEntered

    private void ptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptMouseExited
       pt.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_ptMouseExited

    private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logoMouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
        btn_logout.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
        btn_logout.setForeground(new Color(0xFF5151));
    }//GEN-LAST:event_btn_logoutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private komponen.JPANEL BODY;
    private komponen.JPANEL DASHBOARD;
    private javax.swing.JLabel LABEL;
    private javax.swing.JLabel LOGO;
    private javax.swing.JLabel LOGO1;
    private javax.swing.JLabel LOGO3;
    private komponen.JPANEL MENU;
    private komponen.JPANEL TENTANG;
    private komponen.JPANEL VISUALISASI;
    private javax.swing.JLabel btn_logout;
    private komponen.JPANEL btn_mv;
    private javax.swing.JLabel dsb_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private komponen.JPANEL logo;
    private javax.swing.JLabel mv;
    private javax.swing.JLabel pt;
    private javax.swing.JLabel tr_label;
    private javax.swing.JLabel vs_label;
    // End of variables declaration//GEN-END:variables
}
